version: '3.8'

services:
  # --- Database ---
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  # --- Message Broker (Redis) ---
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

  # --- Redis Exporter ---
  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
    depends_on:
      - redis

  # --- Backend API ---
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${BROKER_URL}
    depends_on:
      - postgres
      - redis

  # --- Worker Nodes ---
  worker:
    build: ./worker
    restart: always
    deploy:
      replicas: 2
    environment:
      - BROKER_URL=${BROKER_URL}
    depends_on:
      - redis

  # --- Monitoring (Prometheus) ---
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml' 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_web.yml:/etc/prometheus/web.yml
    ports:
      - "9090:9090"

  # --- Visualization (Grafana) ---
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      # Задаем пароль админа
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - PROMETHEUS_USER=${PROMETHEUS_USER}
      - PROMETHEUS_PASSWORD=${PROMETHEUS_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  pg_data: